id: dfe79a2f-97b2-45e1-ade6-a7c35876e1aa
name: Owner added to high privileged application
description: |
  'An owner was added to application holding high privileged API permissions'
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActiveDirectory
    dataTypes:
      - AuditLogs
queryFrequency: 30m
queryPeriod: 30m
triggerOperator: gt
triggerThreshold: 0
tactics:
  - PrivilegeEscalation
relevantTechniques:
  - T1548
  - T1078
query: |
  AuditLogs
  | where OperationName == "Add owner to application"
  | extend SearchKey = tostring(TargetResources[1].id)
  | join kind=inner _GetWatchlist('HighRiskApps') on SearchKey
  | extend TargetUser = tostring(TargetResources[0].userPrincipalName)
  | extend Actor = tostring(InitiatedBy.user.userPrincipalName)
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: false
    reopenClosedIncident: false
    lookbackDuration: 5h
    matchingMethod: AllEntities
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails: []
eventGroupingSettings:
  aggregationKind: AlertPerResult
entityMappings:
- entityType: Account
  fieldMappings:
    - identifier: FullName
      columnName: TargetUser
- entityType: Account
  fieldMappings:
    - identifier: FullName
      columnName: Actor
suppressionDuration: 5h
suppressionEnabled: false
version: 1.0.0
kind: Scheduled

